baseURL = "https://borggrech.com/"
languageCode = "en-us"
title = "Edward Borg Grech"
theme = "PaperMod"

[params]
  author = "Edward Borg Grech"
  ShowReadingTime = true
  ShowShareButtons = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Thoughts"
    url = "/thoughts/"
    weight = 2
